[files]
extend-exclude = [
  "site/dist",
  "site/node_modules",
  "site/.astro"
]

[default.extend-words]
Arkret = "Arkret"
arkret = "arkret"
CKP = "CKP"
CKPs = "CKPs"
WebVH = "WebVH"
webvh = "webvh"
Soflare = "Soflare"
teabay = "teabay"
soland = "soland"
coauth = "coauth"
floria = "floria"
inkson = "inkson"
sodmin = "sodmin"
cotest = "cotest"
HashiCorp = "HashiCorp"
OpenAPI = "OpenAPI"
OTEL = "OTEL"
OTK = "OTK"
OTKs = "OTKs"
Paired = "Paired"
ESPACE = "ESPACE"
PN = "PN"
Anc = "Anc"
COSE = "COSE"
Iy = "Iy"
Iz = "Iz"
ND = "ND"
OT = "OT"
daa = "daa"
