name: Link check

on:
  pull_request:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "17 5 * * 1"

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: >-
          docker run --rm
          -v "$PWD:/workspace"
          -w /workspace
          lycheeverse/lychee:0.24.2
            --config lychee.toml
            README.md CHANGELOG.md "spec/v1/**/*.md"
